# fly.backend.toml

app = "omnilearn-backend"
primary_region = "sin"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  FLASK_APP = "backend.app"
  FRONTEND_URL = "https://omnilearn-frontend-wandering-rain-4082.fly.dev"
  DATA_DIR = "/app/data"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "intelli_tutor_data"
  destination = "/app/data"

