# fly.toml app configuration file generated for omnilearn-frontend-wandering-rain-4082 on 2025-08-12T14:45:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omnilearn-frontend-wandering-rain-4082'
primary_region = 'sin'

[build]
  dockerfile = 'frontend/Dockerfile'

  [build.args]
    VITE_API_BASE_URL = 'https://omnilearn-backend.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
